const shopActionsTypes = {
    FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
    FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
    FETCH_COLLECTIONS_FEILURE: "FETCH_COLLECTIONS_FEILURE"
}

export default shopActionsTypes;